on:
  push:
    branches: master
  pull_request:
    branches:
      - master

name: pkgdown

jobs:
  pkgdown:

    runs-on: ${{ matrix.config.os }}
    strategy:
      fail-fast: false
      matrix:
        config:
          - {os: macOS-latest,   r: 'release'}

    env:
      R_REMOTES_NO_ERRORS_FROM_WARNINGS: true
      RSPM: ${{ matrix.config.rspm }}
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v2

      - uses: r-lib/actions/setup-r@master
        id: install-r
        with:
          r-version: release

      - uses: r-lib/actions/setup-pandoc@master

      - name: Install pak and query dependencies
        shell: Rscript {0}
        run: |
          install.packages("pak", repos = "https://r-lib.github.io/p/pak/dev/")
          saveRDS(pak::pkg_deps_tree("local::.", dependencies = TRUE), ".github/r-depends.rds")
      - name: Cache R packages
        uses: actions/cache@v2
        with:
          path: ${{ env.R_LIBS_USER }}
          key: ${{ matrix.config.os }}-${{ steps.install-r.outputs.installed-r-version }}-deploy-1-${{ hashFiles('.github/r-depends.rds') }}
          restore-keys: |
            ${{ matrix.config.os }}-${{ steps.install-r.outputs.installed-r-version }}-deploy-
            ${{ matrix.config.os }}-${{ steps.install-r.outputs.installed-r-version }}-

      - name: Install system dependencies
        if: runner.os == 'Linux'
        shell: Rscript {0}
        run: |
          pak::local_system_requirements(execute = TRUE)
      # xquartz and cairo are needed for Cairo package.
      # harfbuzz and fribidi are needed for textshaping package.
      - name: Mac systemdeps
        if: runner.os == 'macOS'
        run: |
          brew cask install xquartz
          brew install cairo
          brew install harfbuzz fribidi

      - name: Install dependencies
        shell: Rscript {0}
        run: |
          pak::pkg_install(c("remotes", "pkgdown"))
          pak::local_install_dev_deps(upgrade = TRUE)
          pak::local_install(upgrade = TRUE)

      - name: Build Site (PR)
        if: github.event_name != 'push'
        shell: Rscript {0}
        run: |
          pkgdown::build_site()

      - name: Validate all topics exist (PR)
        if: github.event_name != 'push'
        shell: Rscript {0}
        run: |
          pkgdown::build_reference_index()
          stopifnot(length(warnings()) == 0)

      - name: git setup
        if: github.event_name == 'push'
        run: |
          git config --local user.email "${GITHUB_ACTOR}@users.noreply.github.com" && \
            git config --local user.name "${GITHUB_ACTOR}"

      - name: Build and Deploy Site
        if: github.event_name == 'push'
        shell: Rscript {0}
        run: |
          pkgdown::deploy_to_branch(new_process = FALSE)
